### Creates the subnets

# private subnet in AZ-1
- name:               Create private Subnet [AZ-1]
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ private_subnet1_cidr }}"
    az:               "{{ vpc_region }}b"
    region:           "{{ vpc_region }}"
    tags:
      Name:           "{{ vpc_name }}-private01"
  register: my_private_subnet_az1

- name:               Set private Subnet ID in variable [AZ-1]
  set_fact:
    private_subnet_az1_id: "{{ my_private_subnet_az1.subnet.id }}"

# private subnet in AZ-2
- name:               Create private Subnet [AZ-2]
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ private_subnet2_cidr }}"
    az:               "{{ vpc_region }}c"
    region:           "{{ vpc_region }}"
    tags:
      Name:           "{{ vpc_name }}-private02"
  register: my_private_subnet_az2

- name:               Set private Subnet ID in variable [AZ-2]
  set_fact:
    private_subnet_az2_id: "{{ my_private_subnet_az2.subnet.id }}"

# private subnet in AZ-3
- name:               Create private Subnet [AZ-3]
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ private_subnet3_cidr }}"
    az:               "{{ vpc_region }}d"
    region:           "{{ vpc_region }}"
    tags:
      Name:           "{{ vpc_name }}-private03"
  register: my_private_subnet_az3

- name:               Set private Subnet ID in variable [AZ-3]
  set_fact:
    private_subnet_az3_id: "{{ my_private_subnet_az3.subnet.id }}"
